name: Deploy Solana Program to Devnet

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Backend/program/**'
      - 'Backend/Anchor.toml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        override: true
    
    - name: Setup Solana
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install Solana CLI
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/v1.18.4/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
    
    - name: Install Anchor
      run: npm install -g @coral-xyz/anchor-cli@0.31.2
    
    - name: Configure Solana CLI
      run: |
        solana config set --url devnet
        solana-keygen new --no-bip39-passphrase --silent --outfile ~/.config/solana/id.json
    
    - name: Build Program
      working-directory: Backend
      run: anchor build
    
    - name: Deploy Program
      working-directory: Backend
      run: |
        anchor deploy --provider.cluster devnet
        echo "Program deployed successfully!"
    
    - name: Get Program ID
      working-directory: Backend
      run: |
        PROGRAM_ID=$(solana address -k target/deploy/lets_cook-keypair.json)
        echo "PROGRAM_ID=$PROGRAM_ID" >> $GITHUB_ENV
        echo "Program ID: $PROGRAM_ID"
        echo "$PROGRAM_ID" > devnet_program_id.txt
    
    - name: Update Frontend Program ID
      run: |
        PROGRAM_ID=${{ env.PROGRAM_ID }}
        echo "Updating frontend with new program ID: $PROGRAM_ID"
        
        # Update Frontend environment files
        sed -i "s/VITE_MAIN_PROGRAM_ID=.*/VITE_MAIN_PROGRAM_ID=$PROGRAM_ID/" Frontend/devnet.env
        sed -i "s/VITE_CITIZENS_PROGRAM_ID=.*/VITE_CITIZENS_PROGRAM_ID=$PROGRAM_ID/" Frontend/devnet.env
        sed -i "s/VITE_LISTINGS_PROGRAM_ID=.*/VITE_LISTINGS_PROGRAM_ID=$PROGRAM_ID/" Frontend/devnet.env
        sed -i "s/VITE_TRANSFER_HOOK_PROGRAM_ID=.*/VITE_TRANSFER_HOOK_PROGRAM_ID=$PROGRAM_ID/" Frontend/devnet.env
        
        # Update Anchor.toml
        sed -i "s/lets_cook = \".*\"/lets_cook = \"$PROGRAM_ID\"/" Backend/Anchor.toml
    
    - name: Commit Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Backend/devnet_program_id.txt Backend/Anchor.toml Frontend/devnet.env
        git commit -m "Deploy program with new ID: ${{ env.PROGRAM_ID }}" || echo "No changes to commit"
    
    - name: Push Changes
      run: git push